name: Bootstrap
description: Bootstrap workflow setup for organization repositories
author: Incognia
inputs:
  install-packages:
    description: Packages to install
    required: false
  setup-go:
    description: Go version to be passed to inloco/actions-setup-go
    required: false
  setup-java:
    description: Java version to be passed to inloco/actions-setup-java
    required: false
  setup-node:
    description: Node version to be passed to actions/setup-node
    required: false
runs:
  using: composite
  steps:
  - name: Export environment and mask secret variables
    uses: inloco/actions-env-context@HEAD

  - name: Install packages
    shell: bash
    if: inputs.install-packages
    run: |
      apt-get update
      apt-get install -y ${{ inputs.install-packages }}

  - name: Installation Access Token
    id: iat
    uses: inloco/actions-githubapp-installationaccesstoken@HEAD
    if: env.GITHUB_APP_ID && env.GITHUB_APP_PK
    with:
      app-id: ${{ env.GITHUB_APP_ID }}
      app-pk: ${{ env.GITHUB_APP_PK }}

  - name: Checkout
    uses: actions/checkout@v2
    with:
      fetch-depth: 0
      submodules: recursive
      token: ${{ steps.iat.outputs.instl-token || github.token }}

  - name: Setup Go
    uses: inloco/actions-setup-go@HEAD
    if: inputs.setup-go
    with:
      go-version: ${{ inputs.setup-go }}

  - name: Setup Java
    uses: inloco/actions-setup-java@HEAD
    if: inputs.setup-java
    with:
      java-version: ${{ inputs.setup-java }}

  - name: Setup Node
    uses: actions/setup-node@v2
    if: inputs.setup-node
    with:
      node-version: ${{ inputs.setup-node }}
